session_name: tmuxp
start_directory: ./
windows:
  - window_name: latest
    focus: True
    panes:
      - shell_command:
        - subl .
  - window_name: git
    shell_command_before:
      - 'pyenv activate blog'
    panes:
      - shell_command:
        - git status
        - open http://localhost:8000
  - window_name: devserver
    shell_command_before:
      - 'pyenv activate blog'
    panes:
      - ./develop_server.sh start
