session_name: tmuxp
start_directory: ./
windows:
  - window_name: git
    shell_command_before:
      - 'pyenv activate blog'
    panes:
      - shell_command:
        - git status
        - open http://localhost:8000
  - window_name: content
    shell_command_before:
      - 'pyenv activate blog'
    panes:
      - pelican content -r
  - window_name: server
    shell_command_before:
      - 'pyenv activate blog'
    panes:
      - cd output && python -m pelican.server
