language: python
python:
  - "2.7"
cache: apt
install:
  - "pip install -r requirements.txt"
script: "pelican content/"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY # Env
  secret_access_key: $AWS_SECRET_KEY # Env
  bucket: markphilpot.com
  endpoint: markphilpot.com.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  skip_cleanup: true
  local-dir: output
  acl: public_read
  detect_encoding: true
notifications:
  email:
    on_failure: always
